import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Shared/Footer";
import { Suspense } from "react";
import Loader from "./components/Shared/Loader";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
 
        <Navbar /> 
       <Suspense fallback={<Loader/>}>
         
       {children}
        <Footer/>
       </Suspense>
      </body>
    </html>
  );
}
